var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$("iframe").each(function(){var a=$(this).attr("src");$(this).attr("src",a)});
function DeleteIndexDB(){try{window.indexedDB.databases().then(function(a){for(var b=0;b<a.length;b++)window.indexedDB.deleteDatabase(a[b].name)}).then(function(){})}catch(a){}}function convertDurationtoSeconds(a){var b=$jscomp.makeIterator(a.split(":"));a=b.next().value;var c=b.next().value;b=b.next().value;return 3600*Number(a)+60*Number(c)+Number(b)}
function TimeInterval(a){var b=Math.floor(a/3600),c=Math.floor((a-3600*b)/60);a=Math.round(100*(a-3600*b-60*c))/100;return b=(10>b?"0"+b:b)+(":"+(10>c?"0"+c:c))+(":"+(10>a?"0"+a:a))}function ClearAllCookies(){document.cookie="no=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;";document.cookie="yes=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;";document.cookie="why=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;"}function DeleteItems(){localStorage.clear()}
function DeleteItem(a){localStorage.removeItem(a)}function SetStorageDA(a,b){try{localStorage.setItem(a,b)}catch(c){return"Det er ikke muligt at gemme s\u00e5 mange spil sekvenser i browserens hukommelse"}return"Spil sekvenser gemt lokalt til offline brug"}function SetStorageEN(a,b){try{localStorage.setItem(a,b)}catch(c){return"It is not possible to store so many play sequences in the browser's memory"}return"Play sequences stored for offline use"}
function GetStorage(a,b){try{return localStorage.getItem(a,b)}catch(c){}return""}function GetStorageItem(a){return localStorage.getItem(a)}function DeleteDB(){window.indexeddb.deletedatabase("_c2savestates")}document.addEventListener("copy",function(a){a.clipboardData.setData("text/plain","")});function StripHtml(a){return(new DOMParser).parseFromString(a,"text/html").body.textContent||""}$(function(){$("#search-form").submit(function(a){a.preventDefault()})});
function search(){$("#results").html("");$("#btn-cnt").html("");var a=$("#query").val();$.get("https://www.googleapis.com/youtube/v3/search",{part:"snippet, id",q:a,type:"video",key:"AIzaSyAShx8QLS_bc-cvTWKPfKdNLq6P79mDifc"},function(a){var b=a.nextPageToken,d=a.prevPageToken,f=a.pageInfo;console.log(a);$.each(a.items,function(a,b){a=getOutput(b);$("#results").append(a)});a=getButtons(d,b,f);$("#results").prepend(a);$("#btn-cnt").append(a)})}
function getOutput(a){var b=a.id.videoId;return'<div class="row"><div class="col-sm-2"><a data-fancybox href="https://www.youtube.com/watch?v='+b+'"><img class="img-fluid" src="'+a.snippet.thumbnails.high.url+'"></a></div><div class="col-sm-10"><h4><a data-fancybox href="https://www.youtube.com/watch?v='+b+'">'+a.snippet.title+'</a></h4><small>By <span class="cTitle">'+a.snippet.channelTitle+"</span> on "+a.snippet.publishedAt+"</small><p>"+a.snippet.description+"</p></div></div>"}
function getButtons(a,b,c){$("#btn-cnt").html("");var d=$("#query").val();a?(console.log(b),a='<div class="button-container"><span class="total-results"><label>Total Results :</label>'+c.totalResults+'</span><button id="next-button" class="btn  animated-button thar-three" data-token="'+b+'" data-query="'+d+'"onclick="nextPage();">Next Page</button><button id="prev-button" class="btn  animated-button thar-four" data-token="'+a+'" data-query="'+d+'"onclick="prevPage();">Previous Page</button><div class="clearfix"></div></div>'):
(a='<div class="button-container"><span class="total-results"><label>Total Results :</label>'+c.totalResults+'</span><button id="next-button" class="btn animated-button thar-three" data-token="'+b+'" data-query="'+d+'"onclick="nextPage();">Next Page</button><div class="clearfix"></div></div>',console.log(b));return a}
function nextPage(){var a=$("#next-button").data("token"),b=$("#next-button").data("query");$("#results").html("");$("#btn-cnt").html("");b=$("#query").val();$.get("https://www.googleapis.com/youtube/v3/search",{part:"snippet, id",q:b,pageToken:a,type:"video",key:"AIzaSyCP-z9Cc33ZJ44GMyBjdAQH23TV1U5woPc"},function(a){var b=a.nextPageToken,c=a.prevPageToken,e=a.pageInfo;console.log(a);$.each(a.items,function(a,b){a=getOutput(b);$("#results").append(a)});a=getButtons(c,b,e);$("#results").prepend(a);
$("#btn-cnt").append(a)})}
function prevPage(){var a=$("#prev-button").data("token"),b=$("#prev-button").data("query");$("#results").html("");$("#btn-cnt").html("");b=$("#query").val();$.get("https://www.googleapis.com/youtube/v3/search",{part:"snippet, id",q:b,pageToken:a,type:"video",key:"AIzaSyAShx8QLS_bc-cvTWKPfKdNLq6P79mDifc"},function(a){var b=a.nextPageToken,c=a.prevPageToken,e=a.pageInfo;console.log(a);$.each(a.items,function(a,b){a=getOutput(b);$("#results").append(a)});a=getButtons(c,b,e);$("#results").prepend(a);
$("#btn-cnt").append(a)})}function getVideo(a){$.ajax({type:"GET",url:"https://www.googleapis.com/youtube/v3/search",data:{key:"AIzaSyCP-z9Cc33ZJ44GMyBjdAQH23TV1U5woPc",q:a,part:"snippet",maxResults:1,type:"video",videoEmbeddable:!0},success:function(a){embedVideo(a)},error:function(a){console.log("Request Failed")}})}
function embedVideo(a){$("iframe").attr("src","https://www.youtube.com/embed/"+a.items[0].id.videoId);$("h3").text(a.items[0].snippet.title);$(".description").text(a.items[0].snippet.description)}getVideo();
